name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Trigger only when a tag starting with 'v' is pushed
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag'
        required: false
        default: 'v1.0.0'
      executable_name:
        description: 'Name of the executable'
        required: true
        default: 'lyrics2ppt.exe'
      upload_artifact:
        description: 'Upload artifact to release'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt
    - run: pyinstaller generate_ppt_from_txt.py --onefile --icon=lyrics2ppt.ico --name=lyrics2ppt
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/lyrics2ppt.exe
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: dist/*

        
  release:
    runs-on: windows-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v2

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: ./dist

    - name: Determine Tag or SHA
      id: determine_tag_or_sha
      run: |
        # if ($env:GITHUB_REF -eq "refs/heads/main") {
          echo "::set-output name=ref::refs/heads/main"
          echo "::set-output name=ref_name::main"
        # } else {
          echo "::set-output name=ref::${{ github.sha }}"
          echo "::set-output name=ref_name::${{ github.sha }}"
        # }

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: 'v1.0.0'
        release_name: Release v1.0.0
        draft: false
        prerelease: false
